### ISSUE TITLE
Questions for surveys

### ISSUE THREAD

**Issue by nataliazv97** [ConsultinginSM/IT-project#2]
Leave your ideas of questions for surveys here.

**Comment by Jojo41** [comment]
Last question : Would you be interested in a travel application which find, organise and regroup all your booking and tickets according to your budget and your priorities such as time of travel, hotel quality or types of visits ?

Third question : Do you feel like booking websites don't take enough into account your priorities when you try to organise your trip ?

Second question : Do you find it easy and quick to organise and book an entire week-end online when you want to visit a city ?

First question : Do you often book online when you are going to travel ?

**Comment by nataliazv97** [comment]
I change some questions a little, i think now better
also, I think that we should add questions like:
Do you like travel? (to clarify if people are interested in travelling)
Are you a student? 
To know better our target audience and to know if there are any differences between answers from students and others, who are working already.
How much time does it take to you to organise your weekend trip? and the variants that they can choose to answer "less than 30 minutes, more than 30 minutes, more than 1 hour, a lot"
maybe also ask "How often do you travel?" (to understand if people who travel a little will be interested in our application)

**Comment by Jojo41** [comment]
Maybe a description like : "This quick quizz aims to test the attractiveness of a new travelling app we are working on. This application will be a tool for anobody who wants to book a week-end in a European city. It will allow really quicker and easier booking, according to your given budget and your travel priorities, and will regroup all your booking and visit tickets in one place."
